import { TrainData } from './types';

// Parsing the user provided JSON into a constant
export const MOCK_DATA: TrainData = {
  "success": true,
  "train_number": "16650",
  "train_name": "Parasuram Express",
  "train_start_date": "2025-12-04",
  "source_stn_name": "KANYAKUMARI",
  "dest_stn_name": "MANGALORE CNTL",
  "run_days": "MON,TUE,WED,THU,FRI,SAT,SUN",
  "update_time": "2025-12-04 16:13:00 +0530",
  "travelling_towards": "Travelling Northwest",
  "distance_from_source": 498,
  "total_distance": 720,
  "current_station_code": "KUL",
  "current_station_name": "KALLAYI~",
  "status": "T",
  "eta": "16:06",
  "etd": "16:06",
  "delay": 0,
  "ahead_distance_text": "Just left",
  "next_stoppage_info": {
    "next_stoppage": "KOZHIKODE",
    "next_stoppage_time_diff": "in 12 mins"
  },
  "upcoming_stations": [
    {
      "si_no": 95,
      "station_code": "CLT",
      "station_name": "KOZHIKODE",
      "distance_from_source": 499,
      "distance_from_current_station_txt": "Next stop 1 km to go",
      "sta": "16:25",
      "std": "17:00",
      "eta": "16:25",
      "etd": "17:00",
      "halt": 35,
      "arrival_delay": 0,
      "platform_number": 4,
    },
    {
      "si_no": 100,
      "station_code": "QLD",
      "station_name": "QUILANDI",
      "distance_from_source": 524,
      "distance_from_current_station_txt": "Next stop 26 kms to go",
      "sta": "17:18",
      "std": "17:19",
      "eta": "17:18",
      "etd": "17:19",
      "halt": 1,
      "arrival_delay": 0,
      "platform_number": 1,
    },
    {
      "si_no": 105,
      "station_code": "BDJ",
      "station_name": "VADAKARA",
      "distance_from_source": 546,
      "distance_from_current_station_txt": "Next stop 48 kms to go",
      "sta": "17:36",
      "std": "17:37",
      "eta": "17:36",
      "etd": "17:37",
      "halt": 1,
      "arrival_delay": 0,
      "platform_number": 2,
    },
    {
        "si_no": 110,
        "station_code": "TLY",
        "station_name": "THALASSERY",
        "distance_from_source": 568,
        "distance_from_current_station_txt": "Next stop 70 kms to go",
        "sta": "18:02",
        "std": "18:03",
        "eta": "18:02",
        "etd": "18:03",
        "halt": 1,
        "arrival_delay": 0,
        "platform_number": 1,
    },
    {
      "si_no": 114,
      "station_code": "CAN",
      "station_name": "KANNUR",
      "distance_from_source": 589,
      "distance_from_current_station_txt": "Next stop 91 kms to go",
      "sta": "18:26",
      "std": "18:29",
      "eta": "18:26",
      "etd": "18:29",
      "halt": 3,
      "arrival_delay": 0,
      "platform_number": 2,
    },
    {
        "si_no": 121,
        "station_code": "PAY",
        "station_name": "PAYYANUR",
        "distance_from_source": 622,
        "distance_from_current_station_txt": "Next stop 124 kms to go",
        "sta": "19:03",
        "std": "19:04",
        "eta": "19:03",
        "etd": "19:04",
        "halt": 1,
        "arrival_delay": 0,
        "platform_number": 1,
    },
     {
      "si_no": 130,
      "station_code": "KGQ",
      "station_name": "KASARAGOD",
      "distance_from_source": 674,
      "distance_from_current_station_txt": "Next stop 176 kms to go",
      "sta": "19:57",
      "std": "19:58",
      "eta": "19:57",
      "etd": "19:58",
      "halt": 1,
      "arrival_delay": 0,
      "platform_number": 2,
    },
    {
      "si_no": 137,
      "station_code": "MAQ",
      "station_name": "MANGALORE CNTL",
      "distance_from_source": 720,
      "distance_from_current_station_txt": "Next stop 222 kms to go",
      "sta": "21:10",
      "std": "21:10",
      "eta": "21:10",
      "etd": "21:10",
      "halt": 0,
      "arrival_delay": 0,
      "platform_number": 2,
    }
  ],
  "previous_stations": [
    {
      "si_no": 1,
      "station_code": "CAPE",
      "station_name": "KANYAKUMARI",
      "distance_from_source": 0,
      "sta": "03:45",
      "std": "03:45",
      "eta": "03:46",
      "etd": "03:46",
      "halt": 0,
      "arrival_delay": 1,
      "platform_number": 3,
    },
    {
      "si_no": 16,
      "station_code": "TVC",
      "station_name": "TRIVANDRUM CENTRAL",
      "distance_from_source": 87,
      "sta": "06:10",
      "std": "06:15",
      "eta": "06:10",
      "etd": "06:20",
      "halt": 10,
      "arrival_delay": 0,
      "platform_number": 1,
    },
    {
      "si_no": 33,
      "station_code": "QLN",
      "station_name": "KOLLAM JN",
      "distance_from_source": 151,
      "sta": "07:23",
      "std": "07:26",
      "eta": "07:34",
      "etd": "07:37",
      "halt": 3,
      "arrival_delay": 11,
      "platform_number": 2,
    },
    {
      "si_no": 46,
      "station_code": "KTYM",
      "station_name": "KOTTAYAM",
      "distance_from_source": 247,
      "sta": "09:20",
      "std": "09:23",
      "eta": "09:43",
      "etd": "09:46",
      "halt": 3,
      "arrival_delay": 23,
      "platform_number": 1,
    },
    {
        "si_no": 59,
        "station_code": "ERN",
        "station_name": "ERNAKULAM TOWN",
        "distance_from_source": 309,
        "sta": "10:50",
        "std": "10:55",
        "eta": "10:52",
        "etd": "10:55",
        "halt": 3,
        "arrival_delay": 2,
        "platform_number": 1,
    },
    {
      "si_no": 73,
      "station_code": "TCR",
      "station_name": "THRISSUR",
      "distance_from_source": 381,
      "sta": "12:26",
      "std": "12:28",
      "eta": "12:44",
      "etd": "12:46",
      "halt": 2,
      "arrival_delay": 18,
      "platform_number": 2,
    },
    {
      "si_no": 80,
      "station_code": "SRR",
      "station_name": "SHORANUR JN",
      "distance_from_source": 413,
      "sta": "14:00",
      "std": "14:05",
      "eta": "13:39",
      "etd": "14:08",
      "halt": 29,
      "arrival_delay": 0,
      "platform_number": 6,
    },
    {
      "si_no": 88,
      "station_code": "TIR",
      "station_name": "TIRUR",
      "distance_from_source": 458,
      "sta": "14:55",
      "std": "14:57",
      "eta": "15:04",
      "etd": "15:06",
      "halt": 2,
      "arrival_delay": 9,
      "platform_number": 1,
    },
    {
      "si_no": 93,
      "station_code": "FK",
      "station_name": "FEROK",
      "distance_from_source": 490,
      "sta": "15:31",
      "std": "15:32",
      "eta": "15:45",
      "etd": "15:46",
      "halt": 1,
      "arrival_delay": 14,
      "platform_number": 2,
    }
  ]
};